name: build-book

on:
  push:
    branches: [ main ] # main 브랜치에 push될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest # Ubuntu 환경에서 실행

    steps:
      - uses: actions/checkout@v2 # 저장소 코드 체크아웃

      - name: Set up Python # Python 환경 설정
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies # Jupyter Book 및 기타 Python 의존성 설치
        run: |
          python -m pip install --upgrade pip
          python -m pip install jupyter-book altair vega_datasets

      - name: Build the book # Jupyter Book 빌드
        run: jb build .

      - name: Deploy to Netlify # Netlify로 배포하는 새로운 단계
        uses: netlify/actions/cli@master # Netlify CLI GitHub Action 사용
        with:
          args: deploy --prod --dir=_build/html # _build/html 디렉토리를 프로덕션으로 배포
        env: # Netlify 인증 정보를 환경 변수로 전달
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} # GitHub Secret 사용
          NETLIFY_SITE_ID: ${{ secrets.NETIFY_SITE_ID }}     # GitHub Secret 사용
